NANAOSECONDS = 1
MICROSECINDS = 1000 * NANAOSECONDS
MILLISECONDS = 1000 * MICROSECINDS
SECONDS = 1000 * MILLISECONDS

MINE_RATE = 4 * SECONDS

STARTING_BALANCE = 1000

MINING_REWARD = 50
MINING_REWARD_INPUT = {'address': '*--official-minning-reward--*'}